// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClP8BWH0o9kp0M1qH5sJuZ6cxTdN8P8oE',
    appId: '1:1067325308812:android:efd5f703902155dd24e0a9',
    messagingSenderId: '1067325308812',
    projectId: 'seriya-9ccfd',
    storageBucket: 'seriya-9ccfd.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg23PndmqoH6jAO__iv3nnVGyVMitusPQ',
    appId: '1:1067325308812:ios:eb6c02e5a28efdae24e0a9',
    messagingSenderId: '1067325308812',
    projectId: 'seriya-9ccfd',
    storageBucket: 'seriya-9ccfd.firebasestorage.app',
    iosBundleId: 'com.example.seriyaApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZlOH6VqSQ3JgD4Os5JD56DLnwd8a610Y',
    appId: '1:1067325308812:web:0048d7f3d8ba4d0524e0a9',
    messagingSenderId: '1067325308812',
    projectId: 'seriya-9ccfd',
    authDomain: 'seriya-9ccfd.firebaseapp.com',
    storageBucket: 'seriya-9ccfd.firebasestorage.app',
    measurementId: 'G-L6SNPH3JFY',
  );
}
